### ISSUE TITLE
tot_obs and tot_f

### ISSUE THREAD

**Issue by csgillespie** [csgillespie/voltagefit#1]
I don't like the `tot_obs` and `tot_f` parameters in the https://github.com/csgillespie/voltagefit/blob/master/R/plot.R

Surely `tot_obs` is just the number of rows. There must be a way of determining `tot_f`

**Comment by csgillespie** [comment]
Also, I think that the function can be simplified to

```
plotweek = function(wafer, curves, orig=TRUE, tot_obs=241, tot_f=193)
{
  v_f=wafer$VG[1:tot_f]
  v_b=wafer$VG[tot_f:tot_obs]

  op = par(mar=c(3,3,2,1), mgp=c(2,0.4,0), tck=-.01,cex.axis=0.9, las=1)
  on.exit(op)

  if(orig) {
    m = max(log(abs(wafer$ID)))
    curves$forward = exp(m/curves$forward[,1])
    curves$backward = exp(m/curves$backward[i,])
  }
  limits = range(curves$backward, curves$forward)

  plot(v_f,curves$forward[1,],type="l",xlab="Vg (V)",ylab="Id (A)",log="y", 
       ylim=limits,
       main=ifelse(orig, "", "Transformed scale"), panel.first=grid())

  for(i in 2:nrow(curves$forward)) {
      lines(v_f, curves$forward[i,], col=i)
  }

  for(i in 1:nrow(curves$backword)) {
      lines(v_b, curves$backward[i,], col=i, lty=2)
  }

  temp = paste("Week", unique(wafer$test_date))
  legend("topleft", temp,col=1:length(unique(wafer$test_date)), lty=1)
  legend("bottomright", c("Forwards","Backwards"), col=1, lty=1:2)
}
```

Would you check and update as appropriate.

**Comment by gawhitaker** [comment]
I think: 
 if(orig) {
    m = max(log(abs(wafer$ID)))
    curves$forward = exp(m/curves$forward)
    curves$backward = exp(m/curves$backward)
  }

and 
  temp = paste(unique(wafer$test_date)) ##as this will allow what ever they name in the wafer   

but other than that it seems to work. I'll also try to make similar changes for plotunder

**Comment by gawhitaker** [comment]
tot_obs and tot_f now removed from all code
