### ISSUE TITLE
Starting conditions for backward curve

### ISSUE THREAD

**Issue by csgillespie** [csgillespie/voltagefit#4]
Instead of

```
 #backwards
        m.nlmb = nlm(minlogcurveb,c(0.01,0.01,0.01,0.01,0.01,0.01),d_backward$VG,
                     max(log(abs(d_backward$ID)))/log(abs(d_backward$ID)),m.nlmf$estimate,iterlim=lim)
```

The intial conditions should be the values obtained in the forward pass. Also the argument in `fitwafer` should be `iterlim` not `lim`

**Comment by gawhitaker** [comment]
lim has been changed to iterlim. I'm still not convinced on the starting conditions as I'm now sure how nlm minimises. I will investigate further

**Comment by gawhitaker** [comment]
As a note, if the starting conditions can be implemented logcurveb can be deleted
